sudo: required
language: generic
services:
  - docker

script:
  - docker build -t weboaks/node-karma-protractor-chrome:debian-$(git rev-parse HEAD) .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push weboaks/node-karma-protractor-chrome:xvfb-$(git rev-parse HEAD)
